var Cbleep = new Audio()
Cbleep.src = "C.wav";
var Dbleep = new Audio()
Dbleep.src = "D.wav";
var Ebleep = new Audio()
Ebleep.src = "E.wav";
var Fbleep = new Audio()
Fbleep.src = "F.wav";
var Gbleep = new Audio()
Gbleep.src = "G.wav";
var Ableep = new Audio()
Ableep.src = "A.wav";
var Bbleep = new Audio()
Bbleep.src = "B.wav";
var C1bleep = new Audio()
C1bleep.src = "C1.wav";
var D1bleep = new Audio()
D1bleep.src = "D1.wav";
var E1bleep = new Audio()
E1bleep.src = "E1.wav";
var F1bleep = new Audio()
F1bleep.src = "F1.wav";
var Csbleep = new Audio()
Csbleep.src = "C_S.wav";
var Dsbleep = new Audio()
Dsbleep.src = "D_s.wav";
var Fsbleep = new Audio()
Fsbleep.src = "F_s.wav";
var Gsbleep = new Audio()
Gsbleep.src = "G_s.wav";
var Asbleep = new Audio()
Asbleep.src = "Bb.wav";
var Cs1bleep = new Audio()
Cs1bleep.src = "C_s1.wav";
var Ds1bleep = new Audio()
Ds1bleep.src = "D_s1.wav";

